[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = [
    "cd poultryManagementSystem",
    "mvn clean package -DskipTests"
]

[start]
cmd = "cd poultryManagementSystem && java -jar target/*.jar"