spring.datasource.url=jdbc:postgresql://nozomi.proxy.rlwy.net:56810/railway
spring.datasource.username=postgres
spring.datasource.password=RssNdsOQiStUlKzNsooDuLrOwhMBsLDn

spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}