spring.datasource.url=jdbc:postgresql://nozomi.proxy.rlwy.net:56810/railway?sslmode=require

spring.datasource.username=postgres

spring.datasource.password=RssNdsOQiStUlKzNsooDuLrOwhMBsLDn

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}