

spring.application.name=poultryManagementSystem

# Use environment variables (from Render)
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:postgresql://dpg-d7fmbv28qa3s73dlmhn0-a.oregon-postgres.render.com:5432/poultrymanagement
spring.datasource.username=poultrymanagement_user
spring.datasource.password=bjMVIXfZtrIi8xsR5dEnt60lLHJURlvU

# PostgreSQL config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0
server.port=${PORT:8080}