spring.application.name=poultryManagementSystem

spring.datasource.url=jdbc:mysql://localhost:3306/poultrymanagement
spring.datasource.username=root
spring.datasource.password=74334374.Ikhe

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.datasource.DriverClassName=com.mysql.cj.jdbc.Driver

